### ISSUE TITLE
最下方的訊息列亂碼

### ISSUE THREAD

**Issue by changchichung** [clamtestbbs/ve#1]
內文可以打中文，但是空格似乎會有問題

然後最下方的訊息提示都是亂碼，請看下圖

![img](https://i.imgur.com/0au8MDU.png)

請問這問題有解嗎？

**Comment by holishing** [comment]
你的locale應該是utf-8，但這個早期留下來的程式中文編碼是 big5

第一種是把那個視窗的終端機locale改成big5

第二種是編譯前自行先把編碼裡面的 big5 轉成utf8



Eric Chang <notifications@github.com>於 2021年1月4日 週一，上午10:40寫道：
